First draft of IPFS Weekly #53
ipfs/roundups pull request #108
Opened 2019-08-01 18:38 UTC by renrutnnej

Looking for feedback and suggestions on this draft by Monday, August 5 at 12pm Central so that we can send it out via TinyLetter (and post on the blog) Tuesday, August 6. 🌞

Thanks!

2019-08-01 19:16 UTC, ianopolous commented
Under IPFS in the wild could we please add:

[Peergos - fast seeking and encrypted history](https://peergos.org/blog#fast_seeking_and_encrypted_history_), 1 August 2019

and under new releases could we please add:

[Peergos v0.1.0](https://alpha.peergos.net/public/peergos/releases/v0.1.0/) - Fast seeking, encrypted history, and space usage display

Many thanks!

2019-08-01 19:59 UTC, Leela-ann commented
Under IPFS in the wild:
SF [IPFS Meet & Hack](https://www.meetup.com/San-Francisco-IPFS/events/261811887/) August 8, 2019

thank you!

2019-08-01 20:01 UTC, renrutnnej commented
> Under IPFS in the wild:
> SF [IPFS Meet & Hack](https://www.meetup.com/San-Francisco-IPFS/events/261811887/) August 8, 2019
> 
> thank you!

Already included under community events. 👍

2019-08-02 16:08 UTC, Leela-ann commented
Thank you!

2019-08-05 18:51 UTC, terichadbourne requested changes
Thanks for the ProtoSchool and Offline Camp callouts, @renrutnnej! Added a couple of suggested tweaks/links.

2019-08-05 18:51 UTC, terichadbourne commented on published/053-2019-august-6.md
> +As the author of a tutorial, you can now present the learner with a multiple-choice quiz after she reads the text of your lesson, adding some interactivity and a chance to check comprehension before
```suggestion
As the author of a tutorial, you can now present the learner with a multiple-choice quiz after she reads the text of your lesson, adding some interactivity and a chance to check comprehension before moving on to the next topic. Learn more about [building ProtoSchool tutorials](https://proto.school/#/build).
```

2019-08-05 18:51 UTC, terichadbourne commented on published/053-2019-august-6.md
> ++ **RESCHEDULED – 27-30 September 2019:** [Offline Camp Oregon](http://offlinefirst.org/camp/reschedule) had to be postoned, but it’s still happening! Here’s past campers’ take on our unique unconfer
```suggestion
+ **RESCHEDULED – 27-30 September 2019:** [Offline Camp Oregon](http://offlinefirst.org/camp) had to be postponed, but it’s still happening! [Hear how past campers describe this unique unconference retreat](https://youtu.be/FNtpPW_7H1k) focused on the [Offline First](http://offlinefirst.org/) approach to web development and design. 
```

2019-08-05 21:06 UTC, renrutnnej commented
@moyid Draft is ready for translation. Thank you 🙏

2019-08-05 21:18 UTC, ianopolous commented
@renrutnnej Just checking if you saw my comment above? None of it seems to be included.

2019-08-05 21:22 UTC, renrutnnej commented
Apologies if I missed your item, I’m working under the weather today trying
to get the newsletter out on its regular schedule.

I will be sure to include in next issue.

On Mon, Aug 5, 2019 at 4:18 PM Dr Ian Preston <notifications@github.com>
wrote:

> @renrutnnej <https://github.com/renrutnnej> Just checking if you saw my
> comment above? None of it seems to be included.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ipfs/newsletter/pull/108?email_source=notifications&email_token=AATWSFOBHIORH2DJ6DNS2C3QDCKJ5A5CNFSM4IITMG7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3TDRKA#issuecomment-518404264>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AATWSFLC6NXXNO7WRPXFIA3QDCKJ5ANCNFSM4IITMG7A>
> .
>

2019-08-05 21:25 UTC, ianopolous commented
@renrutnnej I put in it a 4 days ago specifically to make this mail out. We care a lot about these. What do I need to do ensure inclusion? Can I submit a PR now with it included?

2019-08-05 21:36 UTC, ianopolous commented
@renrutnnej I've made a pr into this branch with my contributions:
https://github.com/ipfs/newsletter/pull/109

2019-08-05 21:45 UTC, ianopolous commented
@momack2 Is there anything we can do about this?

2019-08-06 13:03 UTC, renrutnnej commented
@ianopolous I added your changes this morning. Thank you so much for your patience and support of the newsletter.

2019-08-06 13:05 UTC, renrutnnej commented
@moyid Added minor changes to lines 28 && 53 for translation.

2019-08-06 16:35 UTC, moyid commented
@renrutnnej  ack. I will push my translation to the blog repo after this is published

2019-08-08 00:49 UTC, renrutnnej commented
IPFS Weekly #53 was published

- To the [IPFS blog](https://blog.ipfs.io/weekly-53/)
- Sent to 2864 subscribers [via Tinyletter](https://tinyletter.com/ipfsnewsletter/letters/ipfs-weekly-53)

2019-08-08 00:49 UTC, merged