First draft of IPFS Weekly #64
ipfs/roundups pull request #126
Opened 2019-10-17 16:25 UTC by renrutnnej

Looking for feedback and suggestions on this draft by Monday, October 21 at 12pm Central so that we can send it out via TinyLetter (and post on the blog) Tuesday, October 22. 👻

Thanks!

2019-10-17 19:53 UTC, terichadbourne requested changes
@renrutnnej Suggested a couple of minor copy changes. I'm not seeing the normal buttons to propose them in a way where you can just accept them directly, sorry!

2019-10-17 19:53 UTC, terichadbourne commented on published/064-2019-oct-22.md
> +### WATCH: IPFS Basics Nigh with ProtoSchool Denver
`Nigh` should be `Night` here (their typo, not yours)

2019-10-17 19:53 UTC, terichadbourne commented on published/064-2019-oct-22.md
> ++ **27 October 2019:** [Force Commercial Platform Based on IPFS](https://www.meetup.com/Shanghai-Decentralized-Systems-Meetup-Group/events/265612157/) hosted by IPFS Force, will focus on studying Dec
Suggested rewording to make it more clear that the talk is about IPFS Force, not about IPFS itself: 

`**27 October 2019:** [Force Commercial Platform Based on IPFS](https://www.meetup.com/Shanghai-Decentralized-Systems-Meetup-Group/events/265612157/) This meetup hosted by the IPFS Force Community will introduce the IPFS Force commercial platform, which connects decentralized storage providers and users on top of the IPFS network. Shanghai, China.`

2019-10-18 12:31 UTC, ianopolous commented
@renrutnnej I've added Peergos' latest update and release here:
https://github.com/ipfs/newsletter/pull/127

2019-10-21 19:28 UTC, renrutnnej commented
This draft is ready for translation @moyid. Thank you!

2019-10-22 19:13 UTC, merged