First draft of IPFS Weekly #98
ipfs/roundups pull request #171
Opened 2020-07-24 02:22 UTC by renrutnnej

Please give tips/suggestions/feedback by 12pm Central on Monday, July 27!

To be distributed Tuesday, July 28 around 12pm Central.

2020-07-27 15:46 UTC, serejandmyself reviewed
## People build the coolest stuff with IPFS
* A decentralized, hardcore, uncensored [Twitter analogue](https://cyber.page/ipfs/QmdfKnMkQUDgBa5rK7UiJG4xULRAKttUsEcDJkq5trotjm) that stores your content in IPFS, built on top of the [Cyber protocol](https://cyber.page)

2020-07-27 18:48 UTC, carsonfarmer requested changes
This seems like a clean way to add a suggestion @renrutnnej? Let me know if you'd prefer a proper PR.

2020-07-27 18:48 UTC, carsonfarmer commented on published/098-2020-jul-28.md
> +
```suggestion

[Signed and Encrypted IPLD, Go](https://www.notion.so/Signed-and-Encrypted-data-in-IPFS-e1593e90b56e44c38e165109999782ce): Implement a new Go-based IPLD codec that supports signed and encrypted Blocks, and get paid for it! Externally funded, 3Box and Textile, Remote
```

2020-07-28 22:18 UTC, renrutnnej commented
Thanks @serejandmyself and @carsonfarmer! ☺️

2020-07-29 19:21 UTC, merged